# config.yml
title: Rahul Bali's Portfolio Blog
author: Rahul Bali
description: >- # this means to ignore newlines until "baseurl:"
  A portfolio website showcasing my projects and skills. Sectioned blog posts and project pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://snapfast.github.io" # the base hostname & protocol for your site
theme: minima

# version 2.5.3

# Build settings
markdown: kramdown
show_excerpts: true

# headers
header_pages:
  - resume.md
  - writings.md
  - contact.md
