# config.yml
title: Rahul Bali
description: >- # this means to ignore newlines until "baseurl:"
  I'm Rahul Bali, an Engineer with a passion for full-stack development, data visualization, web3 and future of finance.

author:
  name: Rahul Bali
  email: "john.smith@foobar.com"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.rahulbali.in" # the base hostname & protocol for your site

# Social media links
# github_username: snapfast
twitter_username: _rahulbali
linkedin_username: rahulbali2

# analytics
google_analytics: G-N6CPNY8CTG

# version 2.5.3
# theme: minima

# Build settings
remote_theme: "jekyll/minima@1e8a445"

# plugins -- jekyll-feed, jekyll-remote-theme for google analytics
# plugins:
#   - jekyll-remote-theme
#   - jekyll-feed



# minima
minima:
  date_format: "%d %B, %Y"
  hide_site_feed_link: true # hides subscribe link
  social_links:
    - title: at GitHub
      icon: github
      url: "https://github.com/snapfast"
    - title: X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/_rahulbali"
show_excerpts: true

# Build settings
markdown: kramdown
excerpt_separator: "--excerpt" #global excerpt separator for the blog posts

# headers
header_pages:
  - resume.md
  - writings.md
  - careers.md
  - referral.md
  - contact.md
