# config.yml
title: Rahul Bali
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Rahul Bali - Engineer, technologist, and explorer of consciousness. Features technical writings, career resources, and insights on wellness, meditation, and the intersection of technology and human potential.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.rahulbali.in" # the base hostname & protocol for your site

# author
author:
  name: Rahul Bali
  email: "john.smith@foobar.com"

# analytics
google_analytics: G-N6CPNY8CTG

# Build settings
remote_theme: "jekyll/minima@1e8a445"

# plugins -- jekyll-feed, jekyll-remote-theme for google analytics
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# minima
minima:
  skin: auto
  date_format: "%d %B, %Y"
  show_excerpts: true
  social_links:
    - title: at GitHub
      icon: github
      url: "https://github.com/snapfast"
    - title: X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/rrahulbali"

# Build settings
markdown: kramdown
excerpt_separator: "--excerpt" #global excerpt separator for the blog posts

# headers
header_pages:
  - resume.md
  - referral.md
  - contact.md
