# config.yml
title: Rahul Bali
author: snapfast
description: >- # this means to ignore newlines until "baseurl:"
  I'm Rahul Bali, an Engineer with a passion for full-stack development, data visualization, web3 and future of finance.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.rahulbali.in" # the base hostname & protocol for your site

# Social media links
# github_username: snapfast
twitter_username: _rahulbali
linkedin_username: rahulbali2

# analytics
google_analytics: G-N6CPNY8CTG

# version 2.5.3
# theme: minima

# Build settings
remote_theme: "jekyll/minima@1e8a445"

# plugins -- jekyll-feed, jekyll-remote-theme for google analytics
# plugins:
  # - jekyll-remote-theme
  # - jekyll-feed

# minima
minima:
  date_format: "%d %B, %Y"
show_excerpts: true

# Build settings
markdown: kramdown
excerpt_separator: "--excerpt" #global excerpt separator for the blog posts

# headers
header_pages:
  - resume.md
  - writings.md
  - careers.md
  - referral.md
  - contact.md
